### PR TITLE
Implemented 11-test in IBAN checking

### PR DESCRIPTION
**Pull request by MarcelvLaar**
Literally only implemented 11-test, and made sample IBANs correct

### CODE REVIEW

**Comment by MarcelvLaar** [comment]
@stickyPiston review plz plz plz plz plz plz plz

**Comment by MarcelvLaar** [comment]
@stickyPiston please review

**Comment by MarcelvLaar** [comment]
@stickyPiston  @stickyPiston @stickyPiston

**Comment by MarcelvLaar** [comment]
@stickyPiston

**Comment by MarcelvLaar** [comment]
@stickyPiston

**Comment by MarcelvLaar** [comment]
Kom hier kom hier
@stickyPiston **REVIEW**

**Review by stickyPiston — APPROVED** [review]
頑張ったね！

**Comment by MarcelvLaar** [comment]
ありがとう！

**Pull request merged**
